// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gjviimqguevzytldaavk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdqdmlpbXFndWV2enl0bGRhYXZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MzY1NjYsImV4cCI6MjA2NjAxMjU2Nn0.2GrrmFZRuZM5JGqWsHkN6kJJRPXv0HQLiyrEaUbEhxI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);